'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, BarChart3, CalendarDays, CheckCircle2, ChevronRight, Clock3, Mail, Megaphone, ShieldCheck, TrendingUp, UsersRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useAuthStore } from '@/store/auth-store';

type HomeRole='executive'|'marketing'|'service'|'development'|'programming';
const roleFor=(name?:string):HomeRole=>name==='SOCIAL_MANAGER'?'marketing':name==='SALES'?'development':name==='CALENDAR_MEMBER'?'service':'executive';
const roles:{id:HomeRole;label:string}[]=[{id:'executive',label:'Executive'},{id:'marketing',label:'Marketing'},{id:'service',label:'Patron service'},{id:'development',label:'Development'},{id:'programming',label:'Programming'}];
const views={
 executive:{title:'Organization overview',description:'Audience health, event momentum and work that needs attention.',action:['Open board report','/dashboard/analytics'],metrics:[['Active patrons','1,406','+6.4%','/dashboard/crm/contacts'],['Repeat rate','52%','+3.1%','/dashboard/crm/retention'],['Campaign reach','18.2K','+8.7%','/dashboard/marketing/insights'],['Tasks due','7','2 overdue','/dashboard/crm/tasks']]},
 marketing:{title:'Audience growth today',description:'Turn audience signals and upcoming events into safe actions.',action:['Create campaign','/dashboard/marketing/campaigns'],metrics:[['Audience growth','+184','This month','/dashboard/crm/contacts'],['Email eligible','1,239','88%','/dashboard/crm/segments'],['Campaign reach','18.2K','+8.7%','/dashboard/marketing/insights'],['Drafts to review','4','2 social · 2 email','/dashboard/marketing']]},
 service:{title:'Patron service command center',description:'Handle access needs and follow-ups with patron context close by.',action:['Open service queue','/dashboard/crm/tasks'],metrics:[['Open cases','12','4 today','/dashboard/crm/tasks'],['Access notes','7','2 updated','/dashboard/crm/contacts'],['Tasks due','6','1 overdue','/dashboard/crm/tasks'],['Resolved','28','This week','/dashboard/crm/tasks']]},
 development:{title:'Relationships to move forward',description:'Keep superfans, lapsed patrons and follow-ups in one view.',action:['Open task queue','/dashboard/crm/tasks'],metrics:[['Superfans','124','+6.1%','/dashboard/crm/segments'],['Tasks due','9','3 today','/dashboard/crm/tasks'],['Churn risk','207','Needs review','/dashboard/crm/retention'],['Recent notes','18','This week','/dashboard/crm/contacts']]},
 programming:{title:'Program and audience pulse',description:'See upcoming events, audience overlap and season gaps.',action:['Explore audience','/dashboard/crm/segments'],metrics:[['Upcoming events','6','Next 30 days','/dashboard/events'],['Audience overlap','38%','Across programs','/dashboard/crm/segments'],['First-time patrons','286','This season','/dashboard/crm/contacts'],['Tasks due','4','1 today','/dashboard/crm/tasks']]},
} as const;
const queue=[['Review Fall season social draft','Marketing','Today','/dashboard/marketing/social'],['Resolve Meta asset connection','Connection','Action needed','/dashboard/settings/integrations'],['Follow up with first-time patrons','Audience','Tomorrow','/dashboard/crm/segments']];
const campaigns=[['Season announcement','Email','Draft','1,239 eligible'],['Opening night reminder','Social','Draft','Instagram + Facebook'],['Fall season','Paid ads','Needs connection','Meta']];

export function RoleHome(){
 const user=useAuthStore(s=>s.user);const initial=useMemo(()=>roleFor(user?.role?.name),[user?.role?.name]);const[role,setRole]=useState<HomeRole>(initial);const view=views[role];
 return <div className="space-y-5">
  <header className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex flex-wrap items-center gap-2"><div className="inline-flex rounded-lg border bg-white p-1">{roles.map(r=><button key={r.id} onClick={()=>setRole(r.id)} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${role===r.id?'bg-blue-50 text-co-blue':'text-muted-foreground'}`}>{r.label}</button>)}</div><span className="text-xs text-muted-foreground">Sep 1–16 · Updated 2 min ago</span></div><h1 className="text-2xl font-bold">{view.title}</h1><p className="mt-1 text-sm text-muted-foreground">{view.description}</p></div><Button asChild><Link href={view.action[1]}>{view.action[0]}<ArrowRight className="ml-2 h-4 w-4"/></Link></Button></header>

  <Link href="/dashboard/settings/integrations" className="flex items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3"><span className="rounded-lg bg-white p-2 text-amber-700"><AlertTriangle className="h-4 w-4"/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">One connection needs attention</span><span className="block text-xs text-muted-foreground">Select the organization&apos;s Meta Page, Instagram account and Pixel before publishing or ads.</span></span><span className="text-sm font-semibold text-amber-800">Review</span><ChevronRight className="h-4 w-4 text-amber-800"/></Link>

  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{view.metrics.map(([label,value,note,href],i)=>{const Icon=[UsersRound,TrendingUp,Mail,CheckCircle2][i];return <Link key={label} href={href} className="group rounded-xl border bg-white p-4 hover:border-co-blue/40"><div className="flex items-start justify-between"><p className="text-sm font-medium text-muted-foreground">{label}</p><Icon className="h-4 w-4 text-co-blue"/></div><p className="mt-2 text-2xl font-bold">{value}</p><div className="mt-1 flex items-center justify-between text-xs text-muted-foreground"><span>{note}</span><span className="opacity-0 transition-opacity group-hover:opacity-100">View →</span></div></Link>})}</div>

  <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
   <section className="overflow-hidden rounded-xl border bg-white"><div className="flex items-center justify-between border-b px-4 py-3"><div><h2 className="font-semibold">Next event pulse</h2><p className="text-xs text-muted-foreground">Fall season announcement · Oct 18 · Miami</p></div><Button asChild variant="ghost" size="sm"><Link href="/dashboard/marketing">Open marketing</Link></Button></div><div className="grid gap-4 p-4 sm:grid-cols-[160px_1fr]"><div className="grid place-items-center rounded-xl bg-gradient-to-br from-blue-100 to-purple-100 text-center"><div><CalendarDays className="mx-auto h-5 w-5 text-co-blue"/><p className="mt-2 text-2xl font-bold">32</p><p className="text-xs text-muted-foreground">days away</p></div></div><div className="space-y-3">{[['Event page','Ready','emerald'],['Email','Draft','slate'],['Social','2 drafts','slate'],['Paid ads','Needs connection','amber']].map(([a,b,c])=><div key={a} className="flex items-center justify-between border-b pb-2 text-sm last:border-0"><span>{a}</span><span className={c==='amber'?'text-amber-700':c==='emerald'?'text-emerald-700':'text-muted-foreground'}>{b}</span></div>)}</div></div></section>
   <section className="rounded-xl border bg-white"><div className="flex items-center justify-between border-b px-4 py-3"><div><h2 className="font-semibold">What needs action</h2><p className="text-xs text-muted-foreground">Approvals, failures and follow-ups</p></div><Link href="/dashboard/crm/tasks" className="text-xs font-semibold text-co-blue">View all</Link></div><div>{queue.map(([title,type,due,href])=><Link href={href} key={title} className="flex items-center gap-3 border-b px-4 py-3 last:border-0 hover:bg-slate-50"><Clock3 className="h-4 w-4 text-co-blue"/><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{title}</span><span className="text-xs text-muted-foreground">{type}</span></span><span className="text-xs text-muted-foreground">{due}</span></Link>)}</div></section>
  </div>

  <div className="grid gap-4 xl:grid-cols-[1fr_1.15fr_.8fr]">
   <section className="rounded-xl border bg-white p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Audience movement</h2><Link href="/dashboard/crm/segments" className="text-xs font-semibold text-co-blue">View segments</Link></div><div className="mt-4 space-y-4">{[['First-time','286','+12%'],['Repeat','731','+5%'],['Churn risk','207','-3%']].map(([a,b,c])=><div key={a}><div className="flex justify-between text-sm"><span>{a}</span><span><strong>{b}</strong> <span className="text-xs text-muted-foreground">{c}</span></span></div><div className="mt-1 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-co-blue" style={{width:a==='Repeat'?'72%':a==='First-time'?'42%':'28%'}}/></div></div>)}</div></section>
   <section className="overflow-hidden rounded-xl border bg-white"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="font-semibold">Campaign work</h2><Link href="/dashboard/marketing" className="text-xs font-semibold text-co-blue">Open marketing</Link></div>{campaigns.map(([name,channel,status,detail])=><div key={name} className="grid grid-cols-[1fr_80px_110px] items-center border-b px-4 py-3 text-sm last:border-0"><span><span className="block font-semibold">{name}</span><span className="text-xs text-muted-foreground">{detail}</span></span><span className="text-xs text-muted-foreground">{channel}</span><span className="text-xs">{status}</span></div>)}</section>
   <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Data readiness</h2><div className="mt-4 space-y-3 text-sm"><p className="flex gap-2"><ShieldCheck className="h-4 w-4 text-emerald-600"/>Consent rules documented</p><p className="flex gap-2"><BarChart3 className="h-4 w-4 text-amber-600"/>Company contacts API pending</p><p className="flex gap-2"><Megaphone className="h-4 w-4 text-amber-600"/>Social assets not selected</p></div><Button asChild variant="outline" size="sm" className="mt-5 w-full"><Link href="/dashboard/settings/integrations">Review sources</Link></Button></section>
  </div>
 </div>;
}
