import { Bell, CalendarClock, ChevronDown, CircleStop, Clock3, Facebook, Flag, GitBranch, Instagram, Mail, Megaphone, Plus, Search, Tags, UserRoundCog, Webhook } from 'lucide-react';
import { Input } from '@/components/ui/input';
import type { WorkflowNodeType } from '@/store/workflow-builder-store';

export interface PaletteItem { type: WorkflowNodeType; subtype: string; label: string }
const GROUPS = [
 { label:'Triggers', items:[{type:'trigger',subtype:'event_published',label:'Event published',icon:CalendarClock,tone:'text-violet-600 bg-violet-50'},{type:'trigger',subtype:'webhook',label:'Webhook',icon:Webhook,tone:'text-sky-600 bg-sky-50'}]},
 { label:'Messages', items:[{type:'action',subtype:'send_email',label:'Send email',icon:Mail,tone:'text-blue-600 bg-blue-50'},{type:'action',subtype:'notify_staff',label:'Notify staff',icon:Bell,tone:'text-amber-600 bg-amber-50'}]},
 { label:'Social', items:[{type:'action',subtype:'instagram_post',label:'Instagram post',icon:Instagram,tone:'text-fuchsia-600 bg-fuchsia-50'},{type:'action',subtype:'facebook_post',label:'Facebook post',icon:Facebook,tone:'text-[#1877F2] bg-blue-50'},{type:'action',subtype:'tiktok_post',label:'TikTok post',icon:Megaphone,tone:'text-cyan-600 bg-cyan-50'}]},
 { label:'Audience data', items:[{type:'action',subtype:'add_tag',label:'Add tag',icon:Tags,tone:'text-emerald-600 bg-emerald-50'},{type:'action',subtype:'update_field',label:'Update field',icon:UserRoundCog,tone:'text-indigo-600 bg-indigo-50'}]},
 { label:'Logic', items:[{type:'condition',subtype:'contact_filter',label:'If / else',icon:GitBranch,tone:'text-violet-600 bg-violet-50'},{type:'wait',subtype:'fixed_delay',label:'Wait',icon:Clock3,tone:'text-slate-600 bg-slate-100'},{type:'goal',subtype:'conversion',label:'Goal',icon:Flag,tone:'text-emerald-600 bg-emerald-50'},{type:'exit',subtype:'complete',label:'Exit',icon:CircleStop,tone:'text-slate-600 bg-slate-100'}]},
] satisfies Array<{label:string;items:Array<PaletteItem & {icon:typeof Mail;tone:string}>}>;
export function WorkflowPalette({onAdd}:{onAdd:(item:PaletteItem)=>void}){return <aside className="w-72 shrink-0 overflow-y-auto border-r bg-white"><div className="sticky top-0 z-10 border-b bg-white p-4"><p className="text-sm font-semibold">Steps</p><p className="mt-1 text-xs text-muted-foreground">Drag onto the canvas. Setup opens when dropped.</p><div className="relative mt-3"><Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground"/><Input placeholder="Search steps" className="h-9 pl-8 text-xs"/></div></div><div className="space-y-5 p-3">{GROUPS.map(group=><section key={group.label}><p className="mb-2 flex items-center justify-between px-1 text-[11px] font-bold uppercase tracking-wider text-muted-foreground">{group.label}<ChevronDown className="h-3 w-3"/></p><div className="grid grid-cols-2 gap-2">{group.items.map(item=>{const Icon=item.icon;return <button draggable onDragStart={event=>event.dataTransfer.setData('application/cultureowl-step',JSON.stringify({type:item.type,subtype:item.subtype,label:item.label}))} key={item.subtype} onClick={()=>onAdd(item)} className="group flex min-h-20 cursor-grab flex-col items-start justify-between rounded-lg border bg-white p-3 text-left text-xs font-semibold shadow-sm hover:border-co-blue/40 hover:bg-slate-50 active:cursor-grabbing"><span className="flex w-full justify-between"><span className={`rounded-md p-1.5 ${item.tone}`}><Icon className="h-4 w-4"/></span><Plus className="h-3 w-3 text-muted-foreground opacity-0 group-hover:opacity-100"/></span>{item.label}</button>})}</div></section>)}</div></aside>}
