'use client';
import { useState } from 'react';
import { CheckCircle2, Circle, Plus, UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import type { WorkKind } from './task-types';
import { WORK_TYPE_META } from './task-types';

const seed=[{id:1,contact:'Maya Rodriguez',title:'Follow up after first visit',due:'Today',kind:'stewardship' as const,subtype:'Follow-up',done:false},{id:2,contact:'Jordan Lee',title:'Confirm accessibility preference',due:'Today',kind:'service' as const,subtype:'Accessibility',done:false},{id:3,contact:'Alex Morgan',title:'Review post-event feedback',due:'Tomorrow',kind:'survey' as const,subtype:'Post-event feedback',done:false}];
export default function TasksPage(){const [tasks,setTasks]=useState(seed);const [kind,setKind]=useState<'all'|WorkKind>('all');const visible=kind==='all'?tasks:tasks.filter(task=>task.kind===kind);return <div className="space-y-6"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold">Tasks & service</h2><p className="mt-1 text-sm text-muted-foreground">Stewardship, cases and survey follow-up without automatic sends.</p></div><Button className="gap-2"><Plus className="h-4 w-4"/>New task</Button></div><Tabs value={kind} onValueChange={value=>setKind(value as typeof kind)}><TabsList><TabsTrigger value="all">All</TabsTrigger><TabsTrigger value="stewardship">Stewardship</TabsTrigger><TabsTrigger value="service">Service</TabsTrigger><TabsTrigger value="survey">Survey</TabsTrigger></TabsList></Tabs><div className="overflow-hidden rounded-xl border bg-white">{visible.map(task=><div key={task.id} className="flex min-h-14 items-center gap-4 border-b px-4 py-3 last:border-b-0"><button onClick={()=>setTasks(items=>items.map(item=>item.id===task.id?{...item,done:!item.done}:item))} aria-label={task.done?'Reopen task':'Complete task'}>{task.done?<CheckCircle2 className="h-5 w-5 text-emerald-600"/>:<Circle className="h-5 w-5 text-slate-400"/>}</button><div className="min-w-0 flex-1"><p className={task.done?'text-sm line-through text-muted-foreground':'text-sm font-semibold'}>{task.title}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><UserRound className="h-3 w-3"/>{task.contact} · {WORK_TYPE_META[task.kind].label}</p></div><Badge variant="outline">{task.subtype}</Badge><span className="w-20 text-right text-sm text-muted-foreground">{task.due}</span></div>)}</div></div>}
