'use client';
import Link from 'next/link';
import { useState } from 'react';
import { AlertCircle, BarChart3, Plus, Search, TrendingUp, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
const NETWORKS=['Instagram','Facebook','TikTok'] as const;
const FILTERS=['All','Live','Recently ended','Paused','Errored','Inactive'];
export default function GrowthPage(){const[network,setNetwork]=useState<(typeof NETWORKS)[number]>('Instagram');return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Social growth</h1><p className="mt-1 text-sm text-muted-foreground">Grow reach and followers through measurable campaigns, starting with Instagram.</p></div><Button disabled><Plus className="mr-2 h-4 w-4"/>Create growth campaign</Button></div><div className="inline-flex rounded-lg border bg-white p-1">{NETWORKS.map(item=><button key={item} onClick={()=>setNetwork(item)} className={`rounded-md px-4 py-2 text-sm font-medium ${network===item?'bg-blue-50 text-co-blue':'text-muted-foreground'}`}>{item}</button>)}</div><div className="flex items-center justify-between rounded-xl border bg-white px-4 py-3"><div className="flex items-center gap-3"><span className="relative rounded-lg bg-slate-100 p-2"><TrendingUp className="h-5 w-5"/><span className="absolute -right-0.5 -top-0.5 h-2 w-2 animate-pulse rounded-full bg-red-500"/></span><span><span className="block text-sm font-semibold">{network} not connected</span><span className="text-xs text-muted-foreground">Connect the organization&apos;s account to unlock insights and campaigns.</span></span></div><Button asChild size="sm" variant="outline"><Link href="/dashboard/settings/integrations/meta-ads">Review connection</Link></Button></div><div className="grid gap-3 sm:grid-cols-3">{[['Live','0',TrendingUp],['Drafts','1',BarChart3],['Scheduled','0',Users]].map(([label,value,RawIcon])=>{const Icon=RawIcon as typeof TrendingUp;return <div key={String(label)} className="rounded-xl border bg-white p-4"><Icon className="h-4 w-4 text-co-blue"/><p className="mt-2 text-xs text-muted-foreground">{String(label)}</p><p className="text-xl font-bold">{String(value)}</p></div>})}</div><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Search growth campaigns by title"/></div><div className="flex flex-wrap items-center gap-1"><span className="mr-2 text-xs font-bold uppercase text-muted-foreground">Filter</span>{FILTERS.map(filter=><Button key={filter} variant={filter==='All'?'secondary':'ghost'} size="sm">{filter}</Button>)}</div><div className="rounded-xl border bg-white p-8 text-center"><AlertCircle className="mx-auto h-6 w-6 text-slate-400"/><p className="mt-3 font-semibold">No campaigns match this filter</p><p className="mt-1 text-sm text-muted-foreground">The inventory is ready; creation remains disabled until the selected network&apos;s insights, publishing approval and account assets are live.</p></div><p className="text-xs text-muted-foreground">Social growth is a dedicated product view, but production launch follows Meta/Instagram approval and the shared connection foundation.</p></div>}
