"use client";

import { useRef, useState } from "react";
import { Download, ListPlus, Plus, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { Contact } from "../hooks/use-contacts-data";

const properties = ["Seating Preference", "Wheelchair Access Needed", "Referral Source", "Anniversary Date", "Typical Party Size"];

export function ContactsToolbar({contacts,onAdd,onImport}:{contacts:Contact[];onAdd:(contact:Contact)=>void;onImport:(contacts:Contact[])=>void}) {
 const [dialog,setDialog]=useState<"properties"|"add"|"import"|null>(null); const [propertyName,setPropertyName]=useState(""); const [propertyList,setPropertyList]=useState(properties); const file=useRef<HTMLInputElement>(null);
 const exportCsv=()=>{const keys=["firstName","lastName","email","phone","city","zip","totalSpend","totalDonations"] as const; const csv=[keys.join(","),...contacts.map(c=>keys.map(k=>`"${String(c[k]).replaceAll('"','""')}"`).join(","))].join("\n"); const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="cultureowl-contacts.csv";a.click();URL.revokeObjectURL(a.href)};
 const submitAdd=(data:FormData)=>{const firstName=String(data.get("firstName")||"").trim(),lastName=String(data.get("lastName")||"").trim(),email=String(data.get("email")||"").trim();if(!firstName||!lastName||!email)return;onAdd({id:crypto.randomUUID(),firstName,lastName,email,phone:String(data.get("phone")||""),city:String(data.get("city")||""),zip:"",birthday:"",interests:[],tags:[],activityStatus:"New",source:"manual",totalSpend:0,totalDonations:0,eventsPurchased:0,eventsAttended:0,lastActivity:new Date().toISOString().slice(0,10),lastPurchased:null,memberSince:new Date().toISOString().slice(0,10),subscribedEmail:false,subscribedText:false});setDialog(null)};
 const importCsv=async(f:File)=>{const rows=(await f.text()).trim().split(/\r?\n/);const headers=rows.shift()?.split(",").map(x=>x.replaceAll('"','').trim())??[];const added=rows.map((row,i)=>{const v=row.split(",").map(x=>x.replace(/^"|"$/g,"").replaceAll('""','"'));const get=(k:string)=>v[headers.indexOf(k)]||"";return {id:`import-${Date.now()}-${i}`,firstName:get("firstName"),lastName:get("lastName"),email:get("email"),phone:get("phone"),city:get("city"),zip:get("zip"),birthday:"",interests:[],tags:[],activityStatus:"New" as const,source:"manual" as const,totalSpend:Number(get("totalSpend"))||0,totalDonations:Number(get("totalDonations"))||0,eventsPurchased:0,eventsAttended:0,lastActivity:new Date().toISOString().slice(0,10),lastPurchased:null,memberSince:new Date().toISOString().slice(0,10),subscribedEmail:false,subscribedText:false}}).filter(c=>c.email);onImport(added);setDialog(null)};
 return <><div className="flex flex-wrap gap-2"><Button variant="outline" className="gap-2" onClick={()=>setDialog("properties")}><ListPlus className="h-4 w-4"/>Custom Properties</Button><Button variant="outline" className="gap-2" onClick={()=>setDialog("import")}><Upload className="h-4 w-4"/>Import</Button><Button variant="outline" className="gap-2" onClick={exportCsv}><Download className="h-4 w-4"/>Export</Button><Button className="gap-2" onClick={()=>setDialog("add")}><Plus className="h-4 w-4"/>Add Contact</Button></div>
 <Dialog open={dialog==="properties"} onOpenChange={o=>!o&&setDialog(null)}><DialogContent><DialogHeader><DialogTitle>Custom properties</DialogTitle><DialogDescription>Add organization-specific fields to every contact, such as seating preference, accessibility needs, referral source or membership level.</DialogDescription></DialogHeader><div className="space-y-2">{propertyList.map(p=><div key={p} className="rounded-md border px-3 py-2 text-sm">{p}</div>)}</div><div className="flex gap-2"><Input value={propertyName} onChange={e=>setPropertyName(e.target.value)} placeholder="New property name"/><Button onClick={()=>{if(propertyName.trim()){setPropertyList([...propertyList,propertyName.trim()]);setPropertyName("")}}}>Add</Button></div><p className="text-xs text-muted-foreground">Prototype state: definitions are saved for this browser session. Shared schemas need backend persistence.</p></DialogContent></Dialog>
 <Dialog open={dialog==="add"} onOpenChange={o=>!o&&setDialog(null)}><DialogContent><form action={submitAdd} className="space-y-4"><DialogHeader><DialogTitle>Add contact</DialogTitle><DialogDescription>Create a contact in this prototype roster.</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-3"><div><Label>First name</Label><Input name="firstName" required/></div><div><Label>Last name</Label><Input name="lastName" required/></div></div><div><Label>Email</Label><Input name="email" type="email" required/></div><div><Label>Phone</Label><Input name="phone"/></div><div><Label>City</Label><Input name="city"/></div><DialogFooter><Button type="submit">Add contact</Button></DialogFooter></form></DialogContent></Dialog>
 <Dialog open={dialog==="import"} onOpenChange={o=>!o&&setDialog(null)}><DialogContent><DialogHeader><DialogTitle>Import contacts</DialogTitle><DialogDescription>Upload a CSV with firstName, lastName and email columns. Exported CultureOwl CSV files can be re-imported.</DialogDescription></DialogHeader><input ref={file} type="file" accept=".csv,text/csv" className="block w-full text-sm"/><DialogFooter><Button onClick={()=>file.current?.files?.[0]&&importCsv(file.current.files[0])}>Import CSV</Button></DialogFooter></DialogContent></Dialog></>;
}
